#!/bin/sh
set -e
cd $(dirname $0)

echo
read -p '改用 Gitee 镜像仓库拉取 ohmyzsh 安装 (Y/n)? ' r
case $r in '' | y | Y)
   export INSTALLER_URL=https://gitee.com/mirrors/oh-my-zsh/raw/master/tools/install.sh
   export REMOTE=https://gitee.com/mirrors/oh-my-zsh.git
   ;;
esac

RUNZSH=no source ./go

if [ -n "$USE_LOCALIZE" ]; then
   cat src/snippet-localize.zsh >>~/.zshrc.local
fi

exec zsh -l
