#!/bin/sh
set -e
cd $(dirname $0)

function apply_gitee() {
   export INSTALLER_URL=https://gitee.com/mirrors/oh-my-zsh/raw/master/tools/install.sh
   export REMOTE=https://gitee.com/mirrors/oh-my-zsh.git
}

if [ -z "$1" ]; then
   echo
   read -p '改用 Gitee 镜像仓库拉取 ohmyzsh 安装 (Y/n)? ' r
   case $r in '' | y | Y) set -- 1 ;; esac
fi

if [ -n "$1" ]; then apply_gitee; fi

RUNZSH=no source ./go

# todo ...

exec zsh -l
