#!/bin/bash
set -e
cd $(dirname $0)

echo
read -p '改用 Gitee 镜像仓库拉取 ohmyzsh 安装 (Y/n)? ' r
if [[ "$r" =~ ^(Y|y|)$ ]]; then
   export INSTALLER_URL=https://gitee.com/mirrors/oh-my-zsh/raw/master/tools/install.sh
   export REMOTE=https://gitee.com/mirrors/oh-my-zsh.git
fi

./go

read -p '写入 src/snippet-c-postfix.zsh 到 .zshrc.local 中 (Y/n)? ' r
[[ "$r" =~ ^(Y|y|)$ ]] && cat src/snippet-c-postfix.zsh >>~/.zshrc.local
