#!/bin/sh
set -e

cd $(dirname $0)

lib/config-check
printf 'Confirm to setup? (Y/n) '
read r
case $r in
'' | y | Y) ;;
*) exit ;;
esac

lib/sudo-add-packages
lib/install-ohmyzsh
lib/zshrc-tweak
lib/zshrc-custom

source lib/config-load
source lib/api.bash

zshrcSnippetComment='# setup-omz prefer:'
if ! grep -qF "$zshrcSnippetComment" ~/.zshrc; then
	echo >>~/.zshrc
	echo "$zshrcSnippetComment" >>~/.zshrc
	cat template/.zshrc >>~/.zshrc
fi

if [ "$APPLY_ZSHRC_LOCAL" = 1 ]; then
	sed -i '/^source ~\/.zshrc.local$/d' ~/.zshrc
	trimFinalNewlines ~/.zshrc
	echo >>~/.zshrc
	echo 'source ~/.zshrc.local' >>~/.zshrc
	cp -n template/.zshrc.local ~/.zshrc.local
fi

trimFinalNewlines ~/.zshrc

echo 'FINISHED!'
