#!/bin/sh
set -e

cd $(dirname $0)/..
source ./lib/config-load

docfile=$(mktemp)
cat <<END >$docfile
== Check Config ==

Press j, k, d, u to scroll up down.
Press q to continue.

Edit "./config*" before setup. Reference: "./samples/*"

==================

SUDO ADD PACKAGE:

Auto Suggestions          = $SUDO_ADD_AUTOSUGGESTIONS
Syntax Highlight          = $SUDO_ADD_SYNTAXHIGHLIGHT
(For pacman only) pkgfile = $SUDO_ADD_PKGFILE

INSTALL:

Target Path    = $ZSH
Script URL     = $INSTALLER_URL
Repository URL = $REMOTE

TWEAK:

Disable auto update = $DISABLE_AUTOUPDATE

CUSTOM:

Apply recommended theme             = $APPLY_RECOMMENDED_THEME
Apply ./template/.zshrc.plug.loader = $APPLY_ZSHRC_PLUGINS_LOADER
Write your code in ~/.zshrc.local   = $APPLY_ZSHRC_LOCAL
END

if [ "$APPLY_ZSHRC_PLUGINS_LOADER" = 1 ]; then
   cat <<END >>$docfile

PLUGINS LOADER:

Path to loader                = $PATH_TO_PLUGLOADER_SCRIPT
Path to required plugins list = $PATH_TO_PLUGLOADER_LIST
Add recommended plugins       = $APPLY_RECOMMENDED_PLUGINS
END
   if [ "$APPLY_RECOMMENDED_PLUGINS" = 1 ]; then
      cat <<END >>$docfile

Add recommended plugins (enhanced aliases) = $APPLY_RECOMMENDED_PLUGINS_ENHANCED_ALIASES
END
   fi
fi

cat $docfile | less -IS
rm $docfile
