#!/bin/sh

loader=$ZSH_PLUGLOADER
list=$ZSH_PLUGLOADER_LIST

if [ ! -f "$ZSH_PLUGLOADER_LIST" ]; then
    cat snippets/.zshrc.plug.list >$list
fi

if [ "$ADD_ENHANCED_ALIASES_PLUGINS" = 1 ]; then
    echo 'common-aliases globalias' >>$list
fi

[ -x "$(command -v systemctl)" ] && echo systemd >>$list

ensureLineInZshrc() {
    if [ -z "$1" ]; then
        echo >>~/.zshrc
    elif ! grep -qF "$1" ~/.zshrc; then
        echo "$1" >>~/.zshrc
    fi
}

if [ -x "$(command -v dpkg)" ]; then
    osType=$(grep ^ID= /etc/os-release | cut -d= -f2)
    if [ "$osType" = ubuntu ]; then
        echo ubuntu >>$list
    else
        echo debian >>$list
    fi

    ensureLineInZshrc
    ensureLineInZshrc 'unalias acs &>/dev/null'
    ensureLineInZshrc "alias acse='apt-cache search'"
fi

[ -x "$(command -v dnf)" ] && echo dnf >>$list

[ -x "$(command -v pacman)" ] && echo archlinux >>$list

echo >>$loader
cat snippets/.zshrc.plug.loader >>$loader

ignore_list="
cp rm mv grep hgrep z '*'
$(echo {1..9})
tmux kate
"

if grep -q globalias $list; then

    for a in $(zsh -ic alias | grep "='ls " | cut -d= -f1); do
        ignore_list="$ignore_list$a "
    done

    printf "GLOBALIAS_FILTER_VALUES=($(echo $ignore_list | fold -s)\n)\n" >>$loader
fi
