#!/bin/sh

[ -x "$(command -v systemctl)" ] && echo systemd >>$2

if [ -x "$(command -v dpkg)" ]; then
    os_id=$( (
        . /etc/os-release
        echo $ID
    ))
    if [ "$os_id" = ubuntu ]; then
        echo ubuntu >>$2
    else
        echo debian >>$2
    fi
    echo "
unalias acs &>/dev/null
alias acse='apt-cache search'" >>~/.zshrc
fi

[ -x "$(command -v dnf)" ] && echo dnf >>$2

[ -x "$(command -v pacman)" ] && echo archlinux >>$2

echo >>$1
cat src/recommended-plugins-autoloader.zsh >>$1

if grep -q globalias $2; then
    ialist+="do cp rm mv grep hgrep z
$(echo {1..9})
"
    for a in $(zsh -i -c 'compgen -a' | grep ^l); do
        case $(zsh -i -c "alias $a" | cut -d\' -f2) in ls*) ialist+="$a " ;; esac
    done
    ialist=$(echo $ialist | fold -s)
    echo "
GLOBALIAS_FILTER_VALUES=(
$ialist
)" >>$1
fi
